_wandb:
    value:
        cli_version: 0.23.1
        e:
            zelrr5h2tkisukrvorsasm9wiib4ja9m:
                codePath: src\evaluate.py
                codePathLocal: src\evaluate.py
                cpu_count: 6
                cpu_count_logical: 6
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "479192481792"
                        used: "356308504576"
                email: s204229@student.dtu.dk
                executable: C:\Users\soere\anaconda3\envs\02476\python.exe
                git:
                    commit: 01a583d62f52fe0f9e820f3ac698c969f5e52f40
                    remote: https://github.com/sorenstange/02476_Machine_learning_operations_Jan26_Group_26.git
                gpu: NVIDIA GeForce GTX 1660 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1408
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce GTX 1660 SUPER
                      uuid: GPU-ad865b98-2c46-5d95-ac12-59ab78f4c4b6
                host: DESKTOP-KDFK9EE
                memory:
                    total: "17086140416"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\soere\OneDrive\Skrivebord\02476_Machine_learning_operations_Jan26_Group_26\src\evaluate.py
                python: CPython 3.12.12
                root: C:\Users\soere\OneDrive\Skrivebord\02476_Machine_learning_operations_Jan26_Group_26
                startedAt: "2026-01-12T12:59:27.146823Z"
                writerId: zelrr5h2tkisukrvorsasm9wiib4ja9m
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
                - 103
            "2":
                - 1
                - 9
                - 41
                - 50
                - 103
            "3":
                - 2
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 64
