steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-north2-docker.pkg.dev/robust-charge-484208-t4/m21-container-registry/train-rice-classifier',
    '-f',
    'Dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-north2-docker.pkg.dev/robust-charge-484208-t4/m21-container-registry/train-rice-classifier'
  ]
- name: 'gcr.io/cloud-builders/cloud-run'
  id: 'Train model with W&B secret'
  args: [
    'deploy',
    '--image',
    'europe-north2-docker.pkg.dev/robust-charge-484208-t4/m21-container-registry/train-rice-classifier',
    '--command',
    'bash,-c,dvc pull && python src/train.py experiment=resnet',
    '--set-env-vars',
    'WANDB_API_KEY=${_WANDB_API_KEY}',
    '--region',
    'europe-north2'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _WANDB_API_KEY: ${WANDB_API_KEY}