steps:
- name: "alpine"
  id: "Replace values in the training config"
  entrypoint: "sh"
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < "$_VERTEX_TRAIN_CONFIG" > "$_VERTEX_TRAIN_CONFIG.tmp"
      mv "$_VERTEX_TRAIN_CONFIG.tmp" "$_VERTEX_TRAIN_CONFIG"
  secretEnv: ['WANDB_API_KEY']

- name: 'alpine'
  id: "Show config"
  waitFor: ['Replace values in the training config']
  entrypoint: "sh"
  args:
    - "-c"
    - |
      cat "$_VERTEX_TRAIN_CONFIG"

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI'
  waitFor: ['Replace values in the training config']
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west1',
    '--display-name',
    'example-mlops-job',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
  ]
substitutions:
  _VERTEX_TRAIN_CONFIG: 'config.yaml'
availableSecrets:
  secretManager:
  - versionName: projects/robust-charge-484208-t4/secrets/wandb-api-key/versions/latest
    env: 'WANDB_API_KEY'