_wandb:
    value:
        cli_version: 0.23.1
        e:
            b8zqkrf52ympx2fpg160066595vd243j:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510704742400"
                        used: "307812614144"
                email: s204229@student.dtu.dk
                executable: C:\Users\soere\anaconda3\envs\02476\python.exe
                git:
                    commit: 69bdc7bd1beefb8e375966d33220ead824816d8f
                    remote: https://github.com/sorenstange/02476_Machine_learning_operations_Jan26_Group_26.git
                host: stange_lenovo
                memory:
                    total: "16952647680"
                os: Windows-10-10.0.26200-SP0
                program: c:\Users\soere\OneDrive\Skrivebord\02476_Machine_learning_operations\02476_Machine_learning_operations_Jan26_Group_26\src\train.py
                python: CPython 3.11.4
                root: C:\Users\soere\OneDrive\Skrivebord\02476_Machine_learning_operations\02476_Machine_learning_operations_Jan26_Group_26
                startedAt: "2026-01-09T10:37:48.993386Z"
                writerId: b8zqkrf52ympx2fpg160066595vd243j
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
                - 103
            "2":
                - 1
                - 9
                - 41
                - 50
                - 103
            "3":
                - 16
            "4": 3.11.4
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 5
lr:
    value: 0.0001
