_wandb:
    value:
        cli_version: 0.23.1
        e:
            olb86t4phn4kq62ofoltu9xzn7u5yuz1:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510704742400"
                        used: "307829293056"
                email: s204229@student.dtu.dk
                executable: C:\Users\soere\anaconda3\envs\02476_project\python.exe
                git:
                    commit: 48cbf2ee43972ba1c342aa402bb1e12d376ceaf9
                    remote: https://github.com/sorenstange/02476_Machine_learning_operations_Jan26_Group_26.git
                host: stange_lenovo
                memory:
                    total: "16952647680"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\soere\OneDrive\Skrivebord\02476_Machine_learning_operations\02476_Machine_learning_operations_Jan26_Group_26\src\train.py
                python: CPython 3.12.12
                root: C:\Users\soere\OneDrive\Skrivebord\02476_Machine_learning_operations\02476_Machine_learning_operations_Jan26_Group_26
                startedAt: "2026-01-09T10:42:07.631686Z"
                writerId: olb86t4phn4kq62ofoltu9xzn7u5yuz1
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
                - 103
            "2":
                - 1
                - 9
                - 41
                - 50
                - 103
            "3":
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 5
lr:
    value: 0.0001
