_wandb:
    value:
        cli_version: 0.23.1
        e:
            yuk1r23i8hvpjbm0ji28gqtc6hjf9i7g:
                args:
                    - experiment=cnn
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "511010926592"
                        used: "380147826688"
                email: s204206@dtu.dk
                executable: C:\Users\fugle\anaconda3\envs\my_environment\python.exe
                git:
                    commit: 49ab1ff1ffb21251bd5a937aff32af68d896fc3d
                    remote: https://github.com/sorenstange/02476_Machine_learning_operations_Jan26_Group_26
                host: DESKTOP-KFSGT5T
                memory:
                    total: "16441667584"
                os: Windows-11-10.0.26200-SP0
                program: -m src.train
                python: CPython 3.13.11
                root: C:\Users\fugle\OneDrive\DTU_2\MLO\dtu_mlops\github_project\02476_Machine_learning_operations_Jan26_Group_26
                startedAt: "2026-01-19T13:54:59.062674Z"
                writerId: yuk1r23i8hvpjbm0ji28gqtc6hjf9i7g
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 50
                - 63
                - 103
                - 105
                - 106
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 50
                - 63
                - 103
                - 105
                - 106
            "3":
                - 16
            "4": 3.13.11
            "5": 0.23.1
            "6": 4.57.5
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 20
lr:
    value: 0.0001
parameters:
    value:
        batch_size: 64
        conv_layers:
            - 16
            - 32
            - 64
            - 128
        epochs: 20
        fc_layers:
            - 256
            - 128
        input_channels: 1
        input_size:
            - 224
            - 224
        learning_rate: 0.0001
        model_name: custom_cnn
        num_workers: 4
        output_dim: 5
